version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - db
    ports:
      - "8001:8000"
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
    