service: kin-food-hall-serverless-lambda

useDotenv: true

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-optimize
    - serverless-offline
    - serverless-event-body-option
    - serverless-dotenv-plugin
    
provider:
   name: aws
   runtime: nodejs18.x
   region: us-east-1
   environment: 
     NODE_OPTIONS: '--experimental-modules --es-module-specifier-resolution=node'

custom:
  serverless-offline:
    httpPort: ${env:PORT}
    noPrependStageInUrl: true

functions:
    main:
      handler: src/lambda.handler
      url: true
      environment: ${file(./.env.${sls:stage})}
      events:
        - http: 
            method: any
            path: /{any+}