service: kin-food-hall-serverless-lambda

useDotenv: true

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-optimize
    - serverless-offline
    - serverless-event-body-option
    - serverless-dotenv-plugin
    
provider:
   name: aws
   runtime: nodejs18.x
   region: us-east-1
   environment: 
     NODE_OPTIONS: '--experimental-modules --es-module-specifier-resolution=node'

custom:
  serverless-offline:
    httpPort: ${env:PORT}
    noPrependStageInUrl: true

functions:
    main:
      name: main-kin-food-hall-sls-lambda-function
      handler: src/lambda.handler
      url: true
      environment: 
         DB_HOST: ${env:DB_HOST}
         DB_PASSWORD: ${env:DB_PASSWORD}
         DB_USERNAME: ${env:DB_USERNAME}
         DB_PORT: ${env:DB_PORT}
         DB_NAME: ${env:DB_NAME}
         PORT: ${env:PORT}
      events:
        - http: 
            method: any
            path: /{any+}