name: deploy-to-aws-on-pr-dev

on: 
  pull_request:
    branches: [main]

env:
  NODE_ENV: development

jobs:
  run-test-on-push:
    name: initial setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm test
     
  deploy:
    name: deploy
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: install dependencies
        run: npm ci

      - name: severless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          DB_HOST: ${{ secrets.DB_HOST}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
          DB_USERNAME: ${{ secrets.DB_USERNAME}}
          DB_PORT: ${{ secrets.DB_PORT}}
          DB_NAME: ${{ secrets.DB_NAME}}
          PORT: ${{ secrets.PORT}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      
